version: '3'
services:

  web:
    build: ./
    ports:
      - "80:80"
    networks:
      - docker_lr

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_lr
    container_name: elasticsearch

networks:
  docker_lr:
    driver: bridge
